<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document Summary Report - {{ config('app.name') }}</title>
    
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.3;
            color: #333;
            margin: 0;
            padding: 15px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 25px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 15px;
        }
        
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 22px;
        }
        
        .header p {
            margin: 3px 0;
            color: #666;
            font-size: 10px;
        }
        
        .report-info {
            background: #f8f9fa;
            padding: 12px;
            border-radius: 5px;
            margin-bottom: 15px;
        }
        
        .report-info h3 {
            margin: 0 0 8px 0;
            color: #1e40af;
            font-size: 14px;
        }
        
        .filters {
            font-size: 10px;
            background: #e3f2fd;
            padding: 10px;
            border-radius: 3px;
            margin-bottom: 15px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 10px;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        
        th {
            background-color: #1e40af;
            color: white;
            font-weight: bold;
            font-size: 9px;
        }
        
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        .text-center {
            text-align: center;
        }
        
        .status-pending { 
            background-color: #fef3c7; 
            color: #92400e; 
            padding: 2px 6px; 
            border-radius: 10px; 
            font-size: 9px;
        }
        .status-in-progress { 
            background-color: #dbeafe; 
            color: #1e40af; 
            padding: 2px 6px; 
            border-radius: 10px; 
            font-size: 9px;
        }
        .status-completed { 
            background-color: #d1fae5; 
            color: #065f46; 
            padding: 2px 6px; 
            border-radius: 10px; 
            font-size: 9px;
        }
        .status-cancelled { 
            background-color: #fee2e2; 
            color: #991b1b; 
            padding: 2px 6px; 
            border-radius: 10px; 
            font-size: 9px;
        }
        
        .priority-low { color: #10b981; }
        .priority-normal { color: #6b7280; }
        .priority-high { color: #f59e0b; }
        .priority-urgent { color: #ef4444; }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 9px;
            color: #666;
            text-align: center;
        }
        
        .summary-stats {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .stat-item {
            display: table-cell;
            background: #f8f9fa;
            padding: 12px;
            text-align: center;
            border: 1px solid #ddd;
            width: 25%;
        }
        
        .stat-number {
            font-size: 18px;
            font-weight: bold;
            color: #1e40af;
        }
        
        .stat-label {
            font-size: 10px;
            color: #666;
            margin-top: 3px;
        }
        
        .document-title {
            font-weight: bold;
            color: #1e40af;
        }
        
        .tracking-number {
            font-family: monospace;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Document Summary Report</h1>
        <p>{{ config('app.name') }}</p>
        <p>Municipality of Madridejos, Cebu</p>
        <p>Generated on: {{ now()->format('F d, Y \a\t g:i A') }}</p>
    </div>
    
    <!-- Report Information -->
    <div class="report-info">
        <h3>Report Details</h3>
        <p><strong>Total Documents:</strong> {{ count($documents) }}</p>
        <p><strong>Generated by:</strong> {{ Auth::user()->name ?? 'System' }}</p>
        <p><strong>Report Period:</strong> 
            @if(isset($request) && $request->filled('date_from'))
                {{ \Carbon\Carbon::parse($request->date_from)->format('M d, Y') }} to 
                {{ \Carbon\Carbon::parse($request->date_to)->format('M d, Y') }}
            @else
                All Time
            @endif
        </p>
    </div>
    
    <!-- Applied Filters -->
    @if(isset($request) && $request->hasAny(['status', 'priority', 'document_type_id', 'department_id']))
    <div class="filters">
        <strong>Applied Filters:</strong>
        @if($request->filled('status'))
            Status: {{ ucfirst(str_replace('_', ' ', $request->status)) }} |
        @endif
        @if($request->filled('priority'))
            Priority: {{ ucfirst($request->priority) }} |
        @endif
        @if($request->filled('document_type_id'))
            Type: Document Type ID {{ $request->document_type_id }} |
        @endif
        @if($request->filled('department_id'))
            Department: Department ID {{ $request->department_id }}
        @endif
    </div>
    @endif
    
    <!-- Summary Statistics -->
    <div class="summary-stats">
        <div class="stat-item">
            <div class="stat-number">{{ number_format($stats['total']) }}</div>
            <div class="stat-label">Total Documents</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ number_format($stats['pending']) }}</div>
            <div class="stat-label">Pending</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ number_format($stats['in_progress']) }}</div>
            <div class="stat-label">In Progress</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ number_format($stats['completed']) }}</div>
            <div class="stat-label">Completed</div>
        </div>
    </div>
    
    <!-- Documents Table -->
    @if(count($documents) > 0)
    <h3 style="color: #1e40af; margin-bottom: 10px;">Document Details ({{ count($documents) }} documents)</h3>
    <table>
        <thead>
            <tr>
                <th style="width: 12%;">Tracking #</th>
                <th style="width: 25%;">Title</th>
                <th style="width: 12%;">Type</th>
                <th style="width: 15%;">Department</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 8%;">Priority</th>
                <th style="width: 10%;">Created</th>
                <th style="width: 8%;">Completion</th>
            </tr>
        </thead>
        <tbody>
            @foreach($documents->take(50) as $document)
            <tr>
                <td class="tracking-number">{{ $document->tracking_number }}</td>
                <td class="document-title">{{ Str::limit($document->title, 35) }}</td>
                <td>{{ $document->documentType->name }}</td>
                <td>{{ Str::limit($document->currentDepartment->name, 15) }}</td>
                <td class="text-center">
                    <span class="status-{{ $document->status }}">
                        {{ ucfirst(str_replace('_', ' ', $document->status)) }}
                    </span>
                </td>
                <td class="text-center priority-{{ $document->priority }}">
                    ● {{ ucfirst($document->priority) }}
                </td>
                <td class="text-center">{{ $document->created_at->format('M d, Y') }}</td>
                <td class="text-center">
                    {{ $document->actual_completion_date ? $document->actual_completion_date->format('M d, Y') : '-' }}
                </td>
            </tr>
            @endforeach
            
            @if(count($documents) > 50)
            <tr>
                <td colspan="8" style="text-align: center; font-style: italic; background: #f0f0f0;">
                    ... and {{ count($documents) - 50 }} more documents (showing first 50 for PDF)
                </td>
            </tr>
            @endif
        </tbody>
    </table>
    
    <!-- Performance Analysis -->
    <div style="margin-top: 20px; background: #f8f9fa; padding: 12px; border-radius: 5px;">
        <h3 style="margin-top: 0; color: #1e40af;">Performance Analysis</h3>
        @php
            $completionRate = $stats['total'] > 0 ? round(($stats['completed'] / $stats['total']) * 100, 1) : 0;
            $overdueCount = $documents->filter(function($doc) { return $doc->isOverdue(); })->count();
        @endphp
        
        <p><strong>Overall Completion Rate:</strong> {{ $completionRate }}% 
           ({{ number_format($stats['completed']) }} of {{ number_format($stats['total']) }} documents)</p>
        
        @if($overdueCount > 0)
        <p><strong>Overdue Documents:</strong> {{ number_format($overdueCount) }} documents are past their target completion date</p>
        @endif
        
        <p><strong>Recommendations:</strong></p>
        <ul style="margin: 8px 0; font-size: 10px;">
            @if($completionRate < 70)
            <li>Focus on improving document completion processes</li>
            @endif
            @if($stats['pending'] > $stats['completed'])
            <li>Address backlog of pending documents</li>
            @endif
            @if($overdueCount > 0)
            <li>Implement stricter deadline monitoring and reminders</li>
            @endif
            <li>Regular review of document workflows for optimization</li>
        </ul>
    </div>
    
    @else
    <div style="text-align: center; padding: 40px; background: #f8f9fa; border-radius: 5px;">
        <h3 style="color: #666;">No Documents Found</h3>
        <p style="color: #999;">No documents match the specified criteria for this report period.</p>
    </div>
    @endif
    
    <!-- Footer -->
    <div class="footer">
        <p>This report was automatically generated by {{ config('app.name') }}</p>
        <p>Municipality of Madridejos | Document Tracking System</p>
        <p>For questions about this report, contact the IT Department</p>
        <p style="margin-top: 8px; font-size: 8px;">
            Report ID: MDJ-SUM-{{ now()->format('YmdHis') }} | 
            Generated: {{ now()->format('Y-m-d H:i:s') }} | 
            Total Pages: 1
        </p>
    </div>
</body>
</html>