<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Monthly Trends Report - {{ config('app.name') }}</title>
    
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1e40af;
            padding-bottom: 20px;
        }
        
        .header h1 {
            color: #1e40af;
            margin: 0;
            font-size: 24px;
        }
        
        .header p {
            margin: 5px 0;
            color: #666;
        }
        
        .report-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        
        .report-info h3 {
            margin: 0 0 10px 0;
            color: #1e40af;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        th {
            background-color: #1e40af;
            color: white;
            font-weight: bold;
        }
        
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-right {
            text-align: right;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
        }
        
        .summary-box {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        
        .summary-item {
            display: inline-block;
            margin-right: 30px;
            margin-bottom: 10px;
        }
        
        .summary-label {
            font-weight: bold;
            color: #1e40af;
        }
        
        .chart-placeholder {
            background: #f8f9fa;
            border: 2px dashed #ddd;
            padding: 40px;
            text-align: center;
            color: #666;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Monthly Trends Report</h1>
        <p>{{ config('app.name') }}</p>
        <p>Municipality of Madridejos, Cebu</p>
        <p>Generated on: {{ now()->format('F d, Y \a\t g:i A') }}</p>
    </div>
    
    <!-- Report Information -->
    <div class="report-info">
        <h3>Report Details</h3>
        <p><strong>Period:</strong> 12-Month Trend Analysis</p>
        <p><strong>Generated by:</strong> {{ Auth::user()->name ?? 'System' }}</p>
        <p><strong>Department:</strong> {{ Auth::user()->department->name ?? 'All Departments' }}</p>
    </div>
    
    <!-- Summary Statistics -->
    <div class="summary-box">
        <h3 style="margin-top: 0; color: #1e40af;">Summary Statistics</h3>
        @php
            $totalCreated = collect($data)->sum('created');
            $totalCompleted = collect($data)->sum('completed');
            $avgCompletion = $totalCreated > 0 ? round(($totalCompleted / $totalCreated) * 100, 1) : 0;
        @endphp
        
        <div class="summary-item">
            <span class="summary-label">Total Documents Created:</span> {{ number_format($totalCreated) }}
        </div>
        <div class="summary-item">
            <span class="summary-label">Total Completed:</span> {{ number_format($totalCompleted) }}
        </div>
        <div class="summary-item">
            <span class="summary-label">Average Completion Rate:</span> {{ $avgCompletion }}%
        </div>
        <div class="summary-item">
            <span class="summary-label">Report Period:</span> {{ count($data) }} Months
        </div>
    </div>
    
    <!-- Chart Placeholder -->
    <div class="chart-placeholder">
        <h4 style="margin: 0;">Document Activity Trends</h4>
        <p>Chart visualization available in web version</p>
        <p style="font-size: 11px;">Access the online dashboard for interactive charts and real-time data</p>
    </div>
    
    <!-- Monthly Data Table -->
    <h3 style="color: #1e40af;">Monthly Document Activity</h3>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th class="text-center">Documents Created</th>
                <th class="text-center">Documents Completed</th>
                <th class="text-center">Completion Rate</th>
                <th class="text-center">Pending</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $monthData)
            <tr>
                <td><strong>{{ $monthData['month'] }}</strong></td>
                <td class="text-center">{{ number_format($monthData['created']) }}</td>
                <td class="text-center">{{ number_format($monthData['completed']) }}</td>
                <td class="text-center">{{ $monthData['completion_rate'] }}%</td>
                <td class="text-center">{{ number_format($monthData['created'] - $monthData['completed']) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background: #e3f2fd; font-weight: bold;">
                <td>TOTAL</td>
                <td class="text-center">{{ number_format($totalCreated) }}</td>
                <td class="text-center">{{ number_format($totalCompleted) }}</td>
                <td class="text-center">{{ $avgCompletion }}%</td>
                <td class="text-center">{{ number_format($totalCreated - $totalCompleted) }}</td>
            </tr>
        </tfoot>
    </table>
    
    <!-- Analysis Section -->
    <div style="margin-top: 30px;">
        <h3 style="color: #1e40af;">Trend Analysis</h3>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 5px;">
            @php
                $recentMonths = array_slice($data, -3);
                $avgRecentCreated = collect($recentMonths)->avg('created');
                $avgRecentCompleted = collect($recentMonths)->avg('completed');
            @endphp
            
            <p><strong>Recent Performance (Last 3 Months):</strong></p>
            <ul style="margin: 10px 0;">
                <li>Average documents created per month: {{ number_format($avgRecentCreated, 1) }}</li>
                <li>Average documents completed per month: {{ number_format($avgRecentCompleted, 1) }}</li>
                <li>Current trend: 
                    @if($avgRecentCreated > collect($data)->avg('created'))
                        <span style="color: green;">▲ Increasing activity</span>
                    @else
                        <span style="color: orange;">▼ Stable/Decreasing activity</span>
                    @endif
                </li>
            </ul>
            
            <p><strong>Recommendations:</strong></p>
            <ul style="margin: 10px 0;">
                @if($avgCompletion < 80)
                <li>Focus on improving document completion rates through workflow optimization</li>
                @endif
                @if($totalCreated - $totalCompleted > 50)
                <li>Address backlog of pending documents through resource allocation</li>
                @endif
                <li>Continue monitoring monthly trends for process improvement opportunities</li>
                <li>Implement automated reminders for documents approaching deadlines</li>
            </ul>
        </div>
    </div>
    
    <!-- Footer -->
    <div class="footer">
        <p>This report was automatically generated by {{ config('app.name') }}</p>
        <p>Municipality of Madridejos | Document Tracking System</p>
        <p>For questions about this report, contact the IT Department</p>
        <p style="margin-top: 10px; font-size: 9px;">
            Report ID: MDJ-RPT-{{ now()->format('YmdHis') }} | 
            Generated: {{ now()->format('Y-m-d H:i:s') }} | 
            Page 1 of 1
        </p>
    </div>
</body>
</html>